ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS omerta_dead BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS omerta_night BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS mafia_ratio TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS min_players INTEGER NOT NULL DEFAULT 4;
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS max_players INTEGER NOT NULL DEFAULT 30;
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS disabled_items TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS pin_lobby BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE group_settings ADD COLUMN IF NOT EXISTS start_admins_only BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS chat_admins (
    user_id  BIGINT NOT NULL,
    chat_id  BIGINT NOT NULL,
    seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, chat_id)
);
